export const SCHEDULE_DATA = [
  {
    homeTeam: "Los Gringos",
    awayTeam: "Bluebirds",
    winner: "away",
    homeScore: 0,
    awayScore: 3,
    time: "6:30 PM",
    date: "6 May, 2024",
    location: "Augsburg",
    game: 1,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "The Storm",
    winner: "home",
    homeScore: 2,
    awayScore: 1,
    time: "8:30 PM",
    date: "20 May, 2024",
    location: "Augsburg",
    game: 2,
  },
  {
    homeTeam: "JAWA FC",
    awayTeam: "Los Gringos",
    winner: "home",
    homeScore: 3,
    awayScore: 2,
    time: "6:30 PM",
    date: "28 May, 2024",
    location: "UofM - Cleveland & Larpenteur",
    game: 3,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "Thicket Football Club",
    winner: "away",
    homeScore: 1,
    awayScore: 3,
    time: "8:30 PM",
    date: "3 June, 2024",
    location: "Augsburg",
    game: 4,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "Rapacki + Co CPAs",
    winner: "home",
    homeScore: 4,
    awayScore: 1,
    time: "6:30 PM",
    date: "10 June, 2024",
    location: "Augsburg",
    game: 5,
  },
  {
    homeTeam: "Bluebirds",
    awayTeam: "Los Gringos",
    winner: "home",
    homeScore: 6,
    awayScore: 0,
    time: "8:30 PM",
    date: "5 August, 2024 (Rescheduled)",
    location: "Dred Scott - East",
    game: 6,
  },
  {
    homeTeam: "JAWA FC",
    awayTeam: "Los Gringos",
    winner: "tie",
    homeScore: 3,
    awayScore: 3,
    time: "6:30 PM",
    date: "24 June, 2024",
    location: "UofM - Cleveland & Larpenteur - Field A (West)",
    game: 7,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "Thicket Football Club",
    winner: "home",
    homeScore: 3,
    awayScore: 1,
    time: "8:30 PM",
    date: "1 July, 2024",
    location: "Augsburg",
    game: 8,
  },
  {
    homeTeam: "The Storm",
    awayTeam: "Los Gringos",
    winner: "away",
    homeScore: 1,
    awayScore: 2,
    time: "6:30 PM",
    date: "8 July, 2024",
    location: "Eden Prairie HS",
    game: 9,
  },
  {
    homeTeam: "Rapacki + Co CPAs",
    awayTeam: "Los Gringos",
    winner: "home",
    homeScore: 5,
    awayScore: 2,
    time: "6:30 PM",
    date: "15 July, 2024",
    location: "Woodbury Fields",
    game: 10,
  },
  {
    homeTeam: "Bluebirds",
    awayTeam: "Los Gringos",
    winner: "home",
    homeScore: 2,
    awayScore: 1,
    time: "6:30 PM",
    date: "22 July, 2024",
    location: "Dred Scott - East",
    game: 11,
  },
  {
    homeTeam: "JAWA FC",
    awayTeam: "Los Gringos",
    winner: "home",
    homeScore: 4,
    awayScore: 3,
    time: "6:30 PM",
    date: "29 July, 2024",
    location: "UofM - Cleveland & Larpenteur - Field A (West)",
    game: 12,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "The Storm",
    winner: "tie",
    homeScore: 2,
    awayScore: 2,
    time: "8:30 PM",
    date: "5 August, 2024",
    location: "Augsburg",
    game: 13,
  },
  {
    homeTeam: "Thicket Football Club",
    awayTeam: "Los Gringos",
    winner: null,
    homeScore: null,
    awayScore: null,
    time: "6:30 PM",
    date: "12 August, 2024",
    location: "McMurray - East",
    game: 14,
  },
];

export const GA_DATA = [
  { name: "Eduardo", goals: 5, assists: 7 },
  { name: "Joel", goals: 0, assists: 1 },
  { name: "Brian C.", goals: 3, assists: 1 },
  { name: "Brian M.", goals: 0, assists: 1 },
  { name: "Adam", goals: 1, assists: 0 },
  { name: "Mahmoud", goals: 5, assists: 4 },
  { name: "Carlos", goals: 2, assists: 1 },
  { name: "Marvin", goals: 4, assists: 2 },
  { name: "Jubair", goals: 1, assists: 1 },
  { name: "Dario", goals: 1, assists: 0 },
  { name: "Michel", goals: 1, assists: 0 },
  { name: "Ernesto", goals: 1, assists: 0 },
  { name: "Colin", goals: 0, assists: 1 },
];

export const ATTENDANCE_DATA = [
  {
    attendees: [
      "Adam",
      "Andy T",
      "Andres",
      "Brian C.",
      "Carlos",
      "Colin",
      "Craig",
      "Dario",
      "Eduardo",
      "Fidel",
      "Jeff",
      "Joel",
      "Jubair",
      "Mahmoud",
      "Marvin",
      "Matt",
      "Pilo",
      "Tanner",
    ],
    scorers: [],
    game: 1,
  },
  {
    attendees: [
      "Adam",
      "Andy T",
      "Andres",
      "Brian C.",
      "Brian M.",
      "Carlos",
      "Dario",
      "Eduardo",
      "Ernesto",
      "Fidel",
      "Jeff",
      "Joel",
      "Jubair",
      "Luis",
      "Matt",
      "Michel",
      "Pilo",
      "Tanner",
    ],
    scorers: ["⚽ Eduardo 🎯 Joel", "⚽ Brian C. 🎯 Brian M."],
    game: 2,
  },
  {
    attendees: [
      "Adam",
      "Andres",
      "Andy T",
      "Brian C.",
      "Brian M.",
      "Carlos",
      "Eduardo",
      "Fidel",
      "Jeff",
      "Joel",
      "Jubair",
      "Luis",
      "Pilo",
      "Tanner",
    ],
    scorers: ["⚽ Adam 🎯 Brian C.", "⚽ Brian C. 🎯 Eduardo"],
    game: 3,
  },
  {
    attendees: [
      "Andres",
      "Adam",
      "Dario",
      "Jubair",
      "Joel",
      "Brian C.",
      "Carlos",
      "Joel",
      "Ernesto",
      "Eduardo",
      "Tanner",
      "Brian M.",
      "Andy T.",
      "Pilo",
      "Luis",
      "Jeff",
      "Marvin",
      "Mahmoud",
      "Fidel",
    ],
    scorers: ["⚽ Mahmoud 🎯 Carlos"],
    game: 4,
  },
  {
    attendees: [
      "Andres",
      "Christian",
      "Adam",
      "Brian C.",
      "Mahmoud",
      "Brian M.",
      "Tanner",
      "Joel",
      "Pilo",
      "Craig",
      "Colin",
      "Jubair",
      "Luis",
      "Eduardo",
      "Marvin",
      "Jeff",
    ],
    scorers: [
      "⚽ Mahmoud 🎯 Eduardo",
      "⚽ Marvin 🎯 Mahmoud",
      "⚽ Marvin 🎯 Eduardo",
      "⚽ Eduardo 🎯 Jubair",
    ],
    game: 5,
  },
  {
    attendees: [
      "Andres",
      "Jubair",
      "Tanner",
      "Colin",
      "Christian",
      "Jeff",
      "Adam",
      "Mahmoud",
      "Ernesto",
      "Pilo",
      "Marvin",
      "Eduardo",
      "Michel",
      "Andy T",
      "Noah",
    ],
    scorers: [],
    game: 6,
  },
  {
    attendees: [
      "Andres",
      "Carlos",
      "Adam",
      "Jubair",
      "Brian C.",
      "Mahmoud",
      "Joel",
      "Jeff",
      "Tanner",
      "Pilo",
      "Fidel",
      "Craig",
      "Luis",
      "Eduardo",
      "Andy T.",
      "Dario",
      "Marvin",
    ],
    scorers: ["⚽ Dario 🎯 Eduardo", "⚽ Carlos 🥅", "⚽ Jubair 🎯 Mahmoud"],
    game: 7,
  },
  {
    attendees: [
      "Andres",
      "Adam",
      "Mahmoud",
      "Jeff",
      "Carlos",
      "Dario",
      "Christian",
      "Marvin",
      "Colin",
      "Jubair",
      "Brian C.",
      "Pilo",
      "Luis",
      "Matt",
      "Fidel",
      "Eduardo",
      "Ernesto",
      "Andy T.",
    ],
    scorers: ["⚽ Eduardo 🎯 Mahmoud", "⚽ Mahmoud 🎯 Eduardo", "⚽ Carlos 🥅"],
    game: 8,
  },
  {
    attendees: [
      "Andres",
      "Dario",
      "Ernesto",
      "Andy T.",
      "Jubair",
      "Tanner",
      "Christian",
      "Adam",
      "Brian C.",
      "Joel",
      "Jeff",
      "Marvin",
      "Colin",
      "Pilo",
      "Brian M.",
      "Eduardo",
    ],
    scorers: ["⚽ Marvin 🎯 Eduardo", "⚽ Brian C. 🥅"],
    game: 9,
  },
  {
    attendees: [
      "Andres",
      "Jubair",
      "Brian C.",
      "Eduardo",
      "Jeff",
      "Adam",
      "Brian M.",
      "Pilo",
      "Marvin",
      "Tanner",
      "Ernesto",
      "Andy T.",
      "Michel",
    ],
    scorers: ["⚽ Marvin 🎯 Adam", "⚽ Michel"],
    game: 10,
  },
  {
    attendees: [
      "Andres",
      "Ernesto",
      "Carlos",
      "Adam",
      "Dario",
      "Jubair",
      "Pilo",
      "Brian C.",
      "Mahmoud",
      "Luis",
      "Jeff",
      "Andy T.",
      "Marvin",
      "Colin",
      "Eduardo",
    ],
    scorers: ["⚽ Mahmoud 🎯 Eduardo"],
    game: 11,
  },
  {
    attendees: [
      "Andres",
      "Jubair",
      "Adam",
      "Carlos",
      "Tanner",
      "Michel",
      "Mahmoud",
      "Pilo",
      "Brian C.",
      "Colin",
      "Jeff",
      "Ernesto",
      "Luis",
      "Andy T.",
      "Marvin",
    ],
    scorers: ["⚽ Ernesto 🎯 Mahmoud", "⚽ Marvin", "⚽ Mahmoud"],
    game: 12,
  },
  {
    attendees: [
      "Andres",
      "Ernesto",
      "Jubair",
      "Adam",
      "Colin",
      "Jeff",
      "Mahmoud",
      "Christian",
      "Dario",
      "Eduardo",
      "Marvin",
      "Tanner",
      "Luis",
      "Pilo",
      "Andy T.",
    ],
    scorers: ["⚽ Eduardo 🎯 Marvin", "⚽ Eduardo 🎯 Colin"],
    game: 13,
  },
  {
    attendees: [],
    scorers: [],
    game: 14,
  },
];
