export const SCHEDULE_DATA = [
  {
    homeTeam: "Los Gringos",
    awayTeam: "Bluebirds",
    winner: "away",
    homeScore: 0,
    awayScore: 3,
    time: "6:30 PM",
    date: "6 May, 2024",
    location: "Augsburg",
    game: 1,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "The Storm",
    winner: "home",
    homeScore: 2,
    awayScore: 1,
    time: "8:30 PM",
    date: "20 May, 2024",
    location: "Augsburg",
    game: 2,
  },
  {
    homeTeam: "JAWA FC",
    awayTeam: "Los Gringos",
    winner: "home",
    homeScore: 3,
    awayScore: 2,
    time: "6:30 PM",
    date: "28 May, 2024",
    location: "UofM - Cleveland & Larpenteur",
    game: 3,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "Thicket Football Club",
    winner: "away",
    homeScore: 1,
    awayScore: 3,
    time: "8:30 PM",
    date: "3 June, 2024",
    location: "Augsburg",
    game: 4,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "Rapacki + Co CPAs",
    winner: "home",
    homeScore: 4,
    awayScore: 1,
    time: "6:30 PM",
    date: "10 June, 2024",
    location: "Augsburg",
    game: 5,
  },
  {
    homeTeam: "Bluebirds",
    awayTeam: "Los Gringos",
    winner: null,
    homeScore: null,
    awayScore: null,
    time: "8:30 PM",
    date: "17 June, 2024",
    location: "Dred Scott - East",
    game: 6,
  },
  {
    homeTeam: "JAWA FC",
    awayTeam: "Los Gringos",
    winner: null,
    homeScore: null,
    awayScore: null,
    time: "6:30 PM",
    date: "24 June, 2024",
    location: "UofM - Cleveland & Larpenteur - Field A (West)",
    game: 7,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "Thicket Football Club",
    winner: null,
    homeScore: null,
    awayScore: null,
    time: "8:30 PM",
    date: "1 July, 2024",
    location: "Augsburg",
    game: 8,
  },
  {
    homeTeam: "The Storm",
    awayTeam: "Los Gringos",
    winner: null,
    homeScore: null,
    awayScore: null,
    time: "6:30 PM",
    date: "8 July, 2024",
    location: "Eden Prairie HS",
    game: 9,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "Rapacki + Co CPAs",
    winner: null,
    homeScore: null,
    awayScore: null,
    time: "6:30 PM",
    date: "15 July, 2024",
    location: "Woodbury Fields",
    game: 10,
  },
  {
    homeTeam: "Bluebirds",
    awayTeam: "Los Gringos",
    winner: null,
    homeScore: null,
    awayScore: null,
    time: "6:30 PM",
    date: "22 July, 2024",
    location: "Dred Scott - East",
    game: 11,
  },
  {
    homeTeam: "JAWA FC",
    awayTeam: "Los Gringos",
    winner: null,
    homeScore: null,
    awayScore: null,
    time: "6:30 PM",
    date: "29 July, 2024",
    location: "UofM - Cleveland & Larpenteur - Field A (West)",
    game: 12,
  },
  {
    homeTeam: "Los Gringos",
    awayTeam: "The Storm",
    winner: null,
    homeScore: null,
    awayScore: null,
    time: "8:30 PM",
    date: "5 August, 2024",
    location: "Augsburg",
    game: 13,
  },
  {
    homeTeam: "Thicket Football Club",
    awayTeam: "Los Gringos",
    winner: null,
    homeScore: null,
    awayScore: null,
    time: "6:30 PM",
    date: "12 August, 2024",
    location: "McMurray - East",
    game: 14,
  },
];

export const GA_DATA = [
  { name: "Eduardo", goals: 2, assists: 3 },
  { name: "Joel", goals: 0, assists: 1 },
  { name: "Brian C.", goals: 2, assists: 1 },
  { name: "Adam", goals: 1, assists: 0 },
  { name: "Mahmoud", goals: 1, assists: 0 },
  { name: "Carlos", goals: 0, assists: 1 },
  { name: "Marvin", goals: 2, assists: 1 },
  { name: "Jubair", goals: 0, assists: 1 },
];

export const ATTENDANCE_DATA = [
  {
    attendees: [
      "Adam",
      "Andy T",
      "Andres",
      "Brian C.",
      "Carlos",
      "Colin",
      "Craig",
      "Dario",
      "Eduardo",
      "Fidel",
      "Jeff",
      "Joel",
      "Jubair",
      "Mahmoud",
      "Marvin",
      "Matt",
      "Pilo",
      "Tanner",
    ],
    scorers: [],
    game: 1,
  },
  {
    attendees: [
      "Adam",
      "Andy T",
      "Andres",
      "Brian C.",
      "Brian M.",
      "Carlos",
      "Dario",
      "Eduardo",
      "Ernesto",
      "Fidel",
      "Jeff",
      "Joel",
      "Jubair",
      "Luis",
      "Matt",
      "Michael",
      "Pilo",
      "Tanner",
    ],
    scorers: ["⚽ Eduardo 🎯 Joel", "⚽ Brian C. 🎯 Brian M."],
    game: 2,
  },
  {
    attendees: [
      "Adam",
      "Andres",
      "Andy T",
      "Brian C.",
      "Brian M.",
      "Carlos",
      "Eduardo",
      "Fidel",
      "Jeff",
      "Joel",
      "Jubair",
      "Luis",
      "Pilo",
      "Tanner",
    ],
    scorers: ["⚽ Adam 🎯 Brian C.", "⚽ Brian C. 🎯 Eduardo"],
    game: 3,
  },
  {
    attendees: [
      "Andres",
      "Adam",
      "Dario",
      "Jubair",
      "Joel",
      "Brian C.",
      "Carlos",
      "Joel",
      "Ernesto",
      "Eduardo",
      "Tanner",
      "Brian M.",
      "Andy T",
      "Pilo",
      "Luis",
      "Jeff",
      "Marvin",
      "Mahmoud",
      "Fidel",
    ],
    scorers: ["⚽ Mahmoud 🎯 Carlos"],
    game: 4,
  },
  {
    attendees: [
      "Andres",
      "Christian",
      "Adam",
      "Brian C.",
      "Mahmoud",
      "Brian M.",
      "Tanner",
      "Joel",
      "Pilo",
      "Craig",
      "Colin",
      "Jubair",
      "Luis",
      "Eduardo",
      "Marvin",
      "Jeff",
    ],
    scorers: [
      "⚽ Mahmoud 🎯 Eduardo",
      "⚽ Marvin 🎯 Mahmoud",
      "⚽ Marvin 🎯 Eduardo",
      "⚽ Eduardo 🎯 Jubair",
    ],
    game: 5,
  },
  {
    attendees: [],
    scorers: [],
    game: 6,
  },
  {
    attendees: [],
    scorers: [],
    game: 7,
  },
  {
    attendees: [],
    scorers: [],
    game: 8,
  },
  {
    attendees: [],
    scorers: [],
    game: 9,
  },
  {
    attendees: [],
    scorers: [],
    game: 10,
  },
  {
    attendees: [],
    scorers: [],
    game: 11,
  },
  {
    attendees: [],
    scorers: [],
    game: 12,
  },
  {
    attendees: [],
    scorers: [],
    game: 13,
  },
  {
    attendees: [],
    scorers: [],
    game: 14,
  },
];
